---
title: "practice lol"
author: "Rachel Li"
date: "3/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("dplyr")
```

```{r}
col_types <- c("factor", "factor", "factor", "factor", "integer", "integer", "factor", "factor", "factor", "integer", "factor", "integer", "integer")
iguodala <- read.csv(file = "../data/andre-iguodala-copy.csv", colClasses = col_types)
```

```{r}
green <- read.csv(file = "../data/draymond-green.csv", colClasses = col_types)
durant <- read.csv(file = "../data/kevin-durant.csv", colClasses = col_types)
thompson <- read.csv(file = "../data/klay-thompson.csv", colClasses = col_types)
curry <- read.csv(file = "../data/stephen-curry.csv", colClasses = col_types)
```

```{r}
iguodala$name <- "Andre Iguodala"
```

```{r}
green$name <- "Draymond Green"
durant$name <- "Kevin Durant"
thompson$name <- "Klay Thompson"
curry$name <- "Stephen Curry"
```

```{r}
iguodala$shot_made_flag <- as.character(iguodala$shot_made_flag)
iguodala$shot_made_flag[iguodala$shot_made_flag == "y"] <- "shot_yes"
iguodala$shot_made_flag[iguodala$shot_made_flag == "n"] <- "shot_no"
iguodala$shot_made_flag <- as.factor(iguodala$shot_made_flag)
```

```{r}
iguodala$period <- as.integer(iguodala$period)
iguodala$minutes <- iguodala$period * 12 - iguodala$minutes_remaining
iguodala$period <- as.factor(iguodala$period)
```

```{r}
sink(file = "../output/andre-iguodala.summary-copy.txt")
summary(iguodala)
sink()
```

```{r}
iguodala
```
```{r}
green$shot_made_flag <- as.character(green$shot_made_flag)
green$shot_made_flag[green$shot_made_flag == "y"] <- "shot_yes"
green$shot_made_flag[green$shot_made_flag == "n"] <- "shot_no"
green$shot_made_flag <- as.factor(green$shot_made_flag)

green$period <- as.integer(green$period)
green$minutes <- green$period * 12 - green$minutes_remaining
green$period <- as.factor(green$period)

sink(file = "../output/draymond-green-summary-copy.txt")
summary(green)
sink()
```

```{r}
durant$shot_made_flag <- as.character(durant$shot_made_flag)
durant$shot_made_flag[durant$shot_made_flag == "y"] <- "shot_yes"
durant$shot_made_flag[durant$shot_made_flag == "n"] <- "shot_no"
durant$shot_made_flag <- as.factor(durant$shot_made_flag)

durant$period <- as.integer(durant$period)
durant$minutes <- durant$period * 12 - durant$minutes_remaining
durant$period <- as.factor(durant$period)

sink(file = "../output/kevin-durant-summary-copy.txt")
summary(durant)
sink()

thompson$shot_made_flag <- as.character(thompson$shot_made_flag)
thompson$shot_made_flag[thompson$shot_made_flag == "y"] <- "shot_yes"
thompson$shot_made_flag[thompson$shot_made_flag == "n"] <- "shot_no"
thompson$shot_made_flag <- as.factor(thompson$shot_made_flag)

thompson$period <- as.integer(thompson$period)
thompson$minutes <- thompson$period * 12 - thompson$minutes_remaining
thompson$period <- as.factor(thompson$period)

sink(file = "../output/klay-thompson-summary-copy.txt")
summary(thompson)
sink()

curry$shot_made_flag <- as.character(curry$shot_made_flag)
curry$shot_made_flag[curry$shot_made_flag == "y"] <- "shot_yes"
curry$shot_made_flag[curry$shot_made_flag == "n"] <- "shot_no"
curry$shot_made_flag <- as.factor(curry$shot_made_flag)

curry$period <- as.integer(curry$period)
curry$minutes <- curry$period * 12 - curry$minutes_remaining
curry$period <- as.factor(curry$period)

sink(file = "../output/stephen-curry-summary-copy.txt")
summary(curry)
sink()
```

```{r}
write.csv(
  x = rbind(iguodala, green, durant, thompson, curry),
  file = "../data/shots-data-copy.csv"
)

```

```{r}
green
```

